### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Wouter01** [SwiftUIX/SwiftUIZ#1]
Hi,

I'm the author of the [SwiftUI-Macros](https://github.com/Wouter01/SwiftUI-Macros) package and noticed that this package is missing an acknowledgement for this. Could you add the acknowledgement to the README, and re-add the original copyright notice to the used files?

Thank you!

**Comment by vmanot** [comment]
@Wouter01 just saw this, thank you for flagging this! I apologize for the oversight (and the delay, this got buried in my notifications for some reason). 

I've updated [EnvironmentValueMacro.swift](https://github.com/SwiftUIX/SwiftUIZ/blob/main/Macros/Intramodular/EnvironmentValueMacro.swift) and [EnvironmentValuesMacro.swift](https://github.com/SwiftUIX/SwiftUIZ/blob/main/Macros/Intramodular/EnvironmentValuesMacro.swift) to re-add the original copyright notice to the used files, and added the acknowledgement to the README.

**Comment by Wouter01** [comment]
Thank you!
